# Generated by Django 3.1.5 on 2021-01-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210122_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='task1',
            name='favourite',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task1',
            name='email',
            field=models.EmailField(max_length=30),
        ),
    ]
